version: '3'

services:
  digitransit-proxy:
    image: stadtnavi/digitransit-proxy:minimal
    ports:
      - 8080:8080
    depends_on:
      - "opentripplanner"
  digitransit-ui:
    image: ${DT_IMAGE}:${DT_TAG}
    environment:
      - CONFIG=${ROUTER:-hb}
      - GEOCODING_BASE_URL=https://photon.stadtnavi.eu/pelias/v1
      - API_URL=${API_URL}
    depends_on:
      - "opentripplanner"
  hsl-map-server:
    image: stadtnavi/hsl-map-server:latest
    environment:
      - OTP_URL=opentripplanner:8080/otp/routers/default/index/graphql
    depends_on:
      - "opentripplanner"
  opentripplanner:
    image: ${OTP_IMAGE}:${OTP_TAG}
    build:
      context: .
      args:
        - OTP_IMAGE=${OTP_IMAGE}
        - OTP_TAG=${OTP_TAG}
        - gtfs_url=${GTFS_URL}
        - osm_pbf_url=${OSM_URL}
        - memory=${GRAPH_BUILD_MEMORY}
    ports:
      - "${OTP_PORT}:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 15s
      timeout: 10s
      retries: 30
